# Generated by Django 5.2.7 on 2025-10-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sensor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(fields=('name', 'location'), name='unique_sensor_per_location'),
        ),
    ]
